# Livenation Serverless Barebone
# @author mindosilalahi@livenation.com
service: ${self:custom.project_name}
frameworkVersion: '3'
variablesResolutionMode: 20210326
configValidationMode: warn

provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  tracing:
    lambda: true
  tags:
    service: ${self:custom.project_name}
    stage: ${self:custom.stage}
  environment: ${file(serverless.env.yml):${self:custom.stage}.env}
  deploymentBucket:
    name: ${file(serverless.env.yml):${self:custom.stage}.deployment_bucket_name}
  iam:
    role:
      Fn::GetAtt:
        - LnLambdaDefaultRole
        - Arn

package:
  patterns:
    - 'app/**'
    - '!node_modules/**'
    - '!app/requirements.txt'
    - '!/**'
    - '!scripts/**'
    - '!CHANGELOG.md'
    - '!README.md'
    - '!Pipfile'
    - '!Pipfile.lock'
    - '!requirements.txt'
    - '!package.json'
    - '!package-lock.json'
    - '!serverless.env.yml'
    - '!cf.resources.yml'
    - '!cf.lambdas.yml'

custom:
  stage: ${opt:stage}
  api_version: 1
  project_name: ln-sls-barebone

resources:
  Resources:
    ${file(cf.resources.yml):custom_resources}

plugins:
  - serverless-python-requirements

functions:
  ${file(cf.lambdas.yml):lambdas}
